services:
  backend-database:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - backend-database
    environment:
      DB_CONNECTION_STRING: '${DB_CONNECTION_STRING}'
      MORALIS_API_KEY: '${MORALIS_API_KEY}'
      FRONTEND_URL: '${FRONTEND_URL}'
      DEPLOYER_URL: '${DEPLOYER_URL}'
      EMAIL_USER: "${EMAIL_USER}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      EMAIL_AUTH_HOST: "${EMAIL_AUTH_HOST}"
      EMAIL_SMTP_HOST: "${EMAIL_SMTP_HOST}"
      WALLET_PRIVATE_KEY_HEX: "${WALLET_PRIVATE_KEY_HEX}"
      WALLET_ADDRESS: "${WALLET_ADDRESS}"
      USE_INSECURE_HTTP: true
      ENVIRONMENT: "docker"
    ports:
      - 8080:8080
    restart: always

volumes:
  postgres_data:
